# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200917_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
