# Generated by Django 3.1.1 on 2020-09-16 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('textoCorpo', models.CharField(max_length=240)),
                ('dataHoraEvento', models.DateTimeField(default=datetime.datetime(2020, 9, 16, 23, 30, 58, 417468, tzinfo=utc))),
                ('bannerEvento', models.ImageField(default='', upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=60)),
                ('segundoNome', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
