# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(max_length=60)),
                ('tituloEvento', models.CharField(max_length=240)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
