# Generated by Django 3.1.1 on 2020-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200921_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bannerEvento',
            field=models.ImageField(default='', upload_to='blog/static/img'),
        ),
    ]
