# Generated by Django 3.1.1 on 2020-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200921_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bannerEvento',
            field=models.ImageField(upload_to='blog/static/img'),
        ),
    ]
