# Generated by Django 3.1.1 on 2020-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200921_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bannerEvento',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
